Update to cpp-driver 2.13 and latest Bincrafters templates
bincrafters/conan-cassandra pull request #1
Opened 2019-09-02 03:44 UTC by sourcedelica

2019-09-02 03:56 UTC, Croydon commented on conanfile.py
>          "OpenSSL/1.0.2o@conan/stable",
Please update OpenSSL

2019-09-02 03:56 UTC, Croydon commented on conanfile.py
> +        cmake.install()
`install` should be executed in package, not in build

2019-09-02 03:57 UTC, Croydon commented on conanfile.py
>              cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = self.options.fPIC
This isn't needed anymore for a while now

2019-09-02 03:58 UTC, Croydon commented on conanfile.py
>      source_subfolder = "source_subfolder"
please rename to `_source_subfolder`

2019-09-02 03:59 UTC, Croydon requested changes
Please update some outdated stuff

many of the things can be automatically updated via [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions)

2019-09-02 03:59 UTC, Croydon commented
I also think that the name cassandra is misleading as it is a driver for it, not the database itself

2019-09-02 15:03 UTC, sourcedelica commented on conanfile.py
> +        cmake.install()
done

2019-09-02 15:03 UTC, sourcedelica commented on conanfile.py
>              cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = self.options.fPIC
done

2019-09-02 15:04 UTC, sourcedelica commented on conanfile.py
>      source_subfolder = "source_subfolder"
done

2019-09-02 15:05 UTC, sourcedelica commented on conanfile.py
>          "OpenSSL/1.0.2o@conan/stable",
done

2019-09-02 15:10 UTC, sourcedelica commented
bincrafters-conventions run.

How about `conan-cassandra-driver`?

2019-09-02 15:12 UTC, closed without merging

2019-09-06 23:19 UTC, uilianries commented
Hi everyone!

So, let's update to `conan-cassandra-driver` ?

2019-09-06 23:22 UTC, sourcedelica commented
That is fine with me

2019-09-07 02:38 UTC, Croydon commented
Are there other cassadra drivers for C/C++ out there or is this the only (known) one?

2019-09-07 14:30 UTC, sourcedelica commented
This is the only C/C++ driver that I know about - it is the official one provided by the developers of Cassandra (Datastax).

2019-09-10 00:09 UTC, Croydon commented
Renamed and added missing attributes via https://github.com/bincrafters/conan-cassandra-driver/commit/434b25b3e657525e70be9529b6c0d7c0e49e7d56